name: CD Deploy Library

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build:storybook

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: db17b9c07d3143836467071da77560d9
          projectName: 'appoinment-system-library'
          directory: 'storybook-static'
