name: Cypress Tests with Dependency and Artifact Caching

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env:
            CYPRESS_USER_TEST_EMAIL: test@test.com
            CYPRESS_USER_TEST_PASSWORD: Tests.15
            CYPRESS_BASE_URL: http://localhost:5173

          install: false
          project: ./
          start: |
            pnpm dev
          wait-on: 'http://[::1]:5173'
          wait-on-timeout: 120
      - name: Show e2e video
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: cypress/videos
  lints:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm lint:check
      - run: pnpm stylelint:check
      - run: pnpm test:unit
      - run: pnpm build
