# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test branch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          TEST_USER_EMAIL: test@test.com
          TEST_USER_PASSWORD: Tests.15
          BASE_URL: http://localhost:5173
          VITE_SERVE_PORT: 5173
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm lint:check
      - run: pnpm stylelint:check
      - run: pnpm test:unit
      - run: pnpm build
      - uses: cypress-io/github-action@v5
        name: Cypress run
        with:
          env: TEST_USER_EMAIL=test@test.com,TEST_USER_PASSWORD=Tests.15,BASE_URL=http://localhost:5173/
          install: false
          project: ./
          start: |
            pnpm dev 
            pnpm test:e2e-cy-cli-action
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
      - uses: actions/upload-artifact@v3
        name: Cypress video
        with:
          name: cypress-videos
          path: cypress/videos
        # env:
        #   TEST_USER_EMAIL: test@test.com
        #   TEST_USER_PASSWORD: Tests.15
        #   CYPRESS_BASE_URL: http://localhost:5173
